### PR TITLE
Double-check pixels before placing them

### PR DESCRIPTION
**Pull request by Ajedi32**
I noticed an issue where sometimes the WebSocket connection doesn't update pixel data fast enough and this script will attempt to "fix" a pixel which is already the right color. This patch causes the script to double-check that the color is still wrong before spending a paint on it.

(Please double-check my work, I'm not 100% sure none of this code broke when I rebased and resolved the resulting conflicts.)

### CODE REVIEW

**Comment by tea-drinker** [comment]
This is a good idea. There will always be a window between verifying a pixel and painting it where we risk missing the update and wasting a click, but I don't think we are getting all of the updates via the websocket.

This update will definitely reduce wasted clicks. I'll review and merge when I'm not in the office.

**Comment by Ajedi32** [comment]
Thanks man, I had a lot of fun working on this. Here's hoping /r/place will be back again someday.

Cheers! :wine_glass:

**Comment by tea-drinker** [comment]
Have you seen https://www.reddit.com/r/Pxlsspace/?

I'm not going to bot the real site, but it's open source so I'm going to keep developing this as websocket practice against a locally hosted server.

Also, I'm putting "PONIES!" at 557, 475.

**Comment by Ajedi32** [comment]
Yeah, that was getting linked quite a bit in /r/place after the game shut down. Pretty neat, but I'm not really all that interested in clones. 3 days was more than enough for me. 😜

**Pull request merged**
